"""empty message

Revision ID: 8d7b045178db
Revises: 
Create Date: 2025-03-21 16:23:09.230552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d7b045178db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('transaction_amount', sa.Float(), nullable=False),
    sa.Column('transaction_channel', sa.String(length=50), nullable=False),
    sa.Column('transaction_payment_mode', sa.String(length=50), nullable=False),
    sa.Column('payment_gateway_bank', sa.String(length=50), nullable=False),
    sa.Column('payer_email', sa.String(length=100), nullable=False),
    sa.Column('payer_mobile', sa.String(length=15), nullable=False),
    sa.Column('payer_card_brand', sa.String(length=50), nullable=True),
    sa.Column('payer_device', sa.String(length=100), nullable=True),
    sa.Column('payer_browser', sa.String(length=100), nullable=True),
    sa.Column('payee_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
